name       : leiningen
version    : 2.9.8
release    : 1
source     :
    - https://github.com/technomancy/leiningen/archive/refs/tags/2.9.8.tar.gz : be299cbd70693213c6887f931327fb9df3bd54930a521d0fc88bea04d55c5cd4
license    : EPL-1.0
component  : programming.tools
networking : yes
summary    : Leiningen is for automating Clojure projects without setting your hair on fire.
description: |
    Leiningen is the easiest way to use Clojure. With a focus on project automation and declarative configuration, it gets out of your way and lets you focus on your code.
environment: |
    export JAVA_CMD=/usr/lib64/openjdk-11/bin/java
builddeps  :
    - openjdk-11
rundeps    :
    - openjdk-11
build      : |
    curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
    chmod a+x ./lein
    cd leiningen-core
    cp $pkgfiles/project.clj ./
    ../lein bootstrap
    ../lein uberjar
    sed -i 's@export LEIN_HOME="${LEIN_HOME:-"$HOME/.lein"}"@export LEIN_HOME="/usr/share/leiningen"@' ../bin/lein

install    : |
    install -Dm00644 ./leiningen-core/target/leiningen-core-2.9.8-standalone.jar $installdir/usr/share/leiningen/self-installs/leiningen-2.9.8-standalone.jar
    install -Dm00755 ./bin/lein $installdir/usr/bin/lein
